CREATE DATABASE movie;
SHOW DATABASES;
use movie;
CREATE TABLE movie(release_date varchar(30),hero varchar(10),heroine varchar(10),place varchar(30),director varchar(10), budget bigint, ratings int,producer varchar(10), release_time int,release_day varchar(10), camera_man varchar(10));
CREATE DATABASE cloth;
SHOW DATABASES;
use cloth;
CREATE TABLE cloth(colour varchar(10),brand varchar(10),size int, price int, manufacture_place varchar(10), manufacture_day varchar(10), budget int, design varchar(30), material varchar(10), manufacture_location varchar(10));
CREATE DATABASE aplications;
SHOW DATABASES;
use applications;
CREATE DATABASE june_7th;
use june_7th;
drop DATABASE movie;
use june_7th;
CREATE TABLE cloth(colour varchar(10),brand varchar(10),size int, price int, manufacture_place varchar(10), manufacture_day varchar(10), budget int, design varchar(30), material varchar(10), manufacture_location varchar(10));
drop DATABASE cloth;
drop DATABASE applications;
use june_7th;
CREATE TABLE applications(name varchar(30),founder varchar(10),versions int,software_used varchar(20),date_of_release int,num_of_applications int, cost int,number_of_updates int, no_of_peoples_involved int);
CREATE TABLE oceans(name_of_ocean varchar(10), water_type varchar(30), depth int, types_of_species int, boating_cost int, width int, total_area int, rivers_joined int, location varchar(10), maximum_visitors int);
CREATE TABLE sports(name_of_sports varchar(20), total_players int, rules varchar(30), court_length int, coach varchar(20), players_name varchar(20), equipment varchar(30), history varchar(30), broadcasting varchar(20), records varchar(20));
CREATE TABLE xworkz(founder varchar(10), no_of_employees varchar(10), started_year int, hr varchar(10), manager varchar(20), vision varchar(10), mission varchar(10), students int, batches int, no_of_tasks int); 
CREATE TABLE charger(name_of_charger varchar(30), company varchar(10), input int, output int, time_taken_to_charge int, cable_length int, customer_reviews varchar(10), warranty int, manufacturing_location varchar(20), ports int);
CREATE TABLE paint(colour varchar(10), container_size int, brand varchar(10), price int, reviews varchar(10), ingredients varchar(20), safety_information varchar(20), type varchar(20), availability varchar(30), id int);
CREATE TABLE name_of_person(no_of_characters varchar(10), length int, meaning varchar(10), first_name varchar(10), last_name varchar(10), gender varchar(10), nationality varchar(20), birth_date int, nick_name varchar(20), prefix varchar(20));
CREATE TABLE emotions(type varchar(10), duration int, cause varchar(20), expression varchar(10), physical_sensation varchar(10), context varchar(20), strategy varchar(20), reason varchar(30), time_to_control int, solution_to_overcome varchar(30));
DROP DATABASE sakila;
